### ISSUE TITLE
Missing reference of JsonDict & JsonPackable

### ISSUE THREAD

**Issue by circler3** [SnowmanTackler/SamSeifert.Velodyne#1]
Hi,
it seems that there are some data structure references missing in the project.

Furthermore, *Utilities* does more that loging. `UnitConverter.DegreesToRadians` in the Utilities is missing.

**Comment by SnowmanTackler** [comment]
This project references my personal utilities library: https://github.com/SnowmanTackler/SamSeifert.Utilities

You need to clone that one as well.  There are no other dependencies.  Please let me know if you have other issues!

**Comment by SnowmanTackler** [comment]
I browsed through your fork.  I can't  believe I missed the hex / dec error!  Everytime we boot I get an unrecognized Lidar Type and just never bothered to debug why.  Thanks for catching that.  I've also found two more bugs you should be aware of on your fork:

When creating UpdateArgs in VLP_16.cs, there is a `st.SocketErrors = timeouts;` line that needs to be changed to `st.Timeouts = timeouts;`  

In VLP_16_Framer.cs, these two lines:
```
this.RecieveBlocks(blck._ChannelData.SubArray(0, 16), blck._Azimuth);	
this.RecieveBlocks(blck._ChannelData.SubArray(0, 16)); // interpolate azimuth
```
need to be changed to:
```
this.RecieveBlocks(blck._ChannelData.SubArray(0, 16), blck._Azimuth);	
this.RecieveBlocks(blck._ChannelData.SubArray(16, 16)); // interpolate azimuth
```
I've changed some of syntax on the master branch in the last week, and tried to add more comments. 
The two changes above are the only functional changes.

**Comment by circler3** [comment]
Hi,
Thx for your reply, I intended to start a PR to fix the issue, but the device was occupied. I was not able to do further test at that moment. I'll sync with your branch. Thank you again~
